# Generated by Django 4.2.4 on 2023-11-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_restaurant_location_alter_restaurant_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
