# Generated by Django 4.2.4 on 2023-10-23 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='post',
            field=models.TextField(null=True),
        ),
    ]
