# Generated by Django 4.2.4 on 2023-10-29 10:41
import random

from django.db import migrations


def add_barcode(apps, schema_editor):
    product = apps.get_model('main_app', 'Product')
    all_products = product.objects.all()
    all_barcodes = random.sample(
        range(100_000_000, 1_000_000_000),
        len(all_products)
    )

    for i in range(len(all_products)):
        product = all_products[i]
        product.barcode = all_barcodes[i]
        product.save()


def reverse_add_barcode(apps, schema_editor):
    product = apps.get_model('main_app', 'Product')
    all_products = product.objects.all()

    for product in all_products:
        product.barcode = 0
        product.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [migrations.RunPython(add_barcode, reverse_code=reverse_add_barcode)
    ]
