# Generated by Django 4.2.4 on 2023-10-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_product_barcode'),
        ('main_app', '0005_auto_20231029_1340'),
    ]

    operations = [
    ]
